name: OpenHands Agent

on:
  push:
    branches: [ main ]    # or whatever branch you’re using
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Start OpenHands
        uses: all-hands-dev/openhands-action@latest
        with:
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
